import type { SubagentDefinition, SubagentContext, SubagentRunResult } from '../../shared/subagent-types';
import { getBedrockClient, getMcpToolsForClaude, executeTool } from '../services/bedrock-client';

const MAX_TOOL_ROUNDS = 20;

const SECURITY_TOOLS = ['sec_userRoles', 'sec_userDbPermissions', 'sec_rolePermissions', 'base_readQuery'];

export const securityAuditDef: SubagentDefinition = {
  id: 'security-audit',
  name: 'Security Audit',
  description: 'Analyzes access rights, roles, and permissions for security anomalies.',
  icon: 'Shield',
  params: [
    {
      key: 'scope',
      label: 'Audit Scope',
      placeholder: 'Username, database name, or "system-wide"',
      required: true,
    },
  ],
};

function buildSecuritySystemPrompt(scope: string): string {
  return `You are a Teradata Security Auditor. Analyze the security posture of the Teradata environment.

## Audit Scope
${scope} — Determine the scope type:
- If scope contains "@" → treat as a username
- If scope is "system-wide" or "all" → full system audit
- Otherwise → treat as a database name

## Available MCP Tools
You have access to these tools (use their discovered parameter names):
- sec_userRoles — List roles assigned to a user
- sec_userDbPermissions — Access rights granted to a user on databases/objects
- sec_rolePermissions — Permissions attached to a role
- base_readQuery — Run arbitrary SQL against Teradata (for DBC views)

## Analysis Checklist

### 1. Access Rights & Role Membership (SECU-02)
- For username scope: query sec_userRoles and sec_userDbPermissions
- For database scope: query base_readQuery to find all users with access to the database
- For system-wide: query base_readQuery against DBC.AccessRightsV for all non-system users

### 2. Overly Permissive Grants (SECU-03)
Run via base_readQuery:
\`\`\`sql
SELECT UserName, DatabaseName, AccessRight, GrantAuthority
FROM DBC.AllRightsV
WHERE (AccessRight = 'CT' OR AccessRight = 'CD' OR AccessRight = 'CR'
       OR AccessRight = 'CA' OR GrantAuthority = 'Y')
  AND UserName NOT IN ('DBC', 'SYSLIB', 'SYSTEMFE', 'TDWM', 'SystemFe', 'Crashdumps', 'dbcmngr', 'SYSUDTLIB', 'SYSBAR', 'SYSJDBC', 'SYSXML')
ORDER BY DatabaseName, UserName
\`\`\`
Flag: Users with ALL privileges, WITH GRANT OPTION, or direct system DB access.

Also check for orphaned grants (direct access bypassing roles):
\`\`\`sql
SELECT a.UserName, a.DatabaseName, a.AccessRight
FROM DBC.AllRightsV a
WHERE a.UserName NOT IN (SELECT DISTINCT Grantee FROM DBC.RoleMembersV)
  AND a.UserName NOT IN ('DBC', 'SYSLIB', 'SYSTEMFE', 'TDWM', 'SystemFe', 'Crashdumps', 'dbcmngr', 'SYSUDTLIB', 'SYSBAR', 'SYSJDBC', 'SYSXML')
  AND a.UserName <> a.DatabaseName
ORDER BY a.UserName
\`\`\`

### 3. Logon Anomalies (SECU-04)
Try this query via base_readQuery — if it fails (DBQL not enabled), note "DBQL logging unavailable — logon analysis skipped" and continue:
\`\`\`sql
SELECT TOP 20 UserName, LogType,
       COUNT(*) AS EventCount,
       MAX(LogDate) AS LastEvent
FROM DBC.LogOnOffV
WHERE LogDate >= DATE - 30
GROUP BY UserName, LogType
HAVING COUNT(*) > 10
ORDER BY EventCount DESC
\`\`\`
Look for: excessive failed logins, off-hours activity, dormant accounts with recent activity.

### 4. Output Format (SECU-05)
Produce a markdown report with this structure:

# Security Audit Report
**Scope:** ${scope}
**Date:** {current date}

## Executive Summary
{Brief overview of findings count by severity}

## Findings

### HIGH Severity
{For each finding:}
#### [H-{N}] {Finding Title}
**Risk:** {description}
**Affected:** {objects/users}
**Remediation:**
\`\`\`sql
{REVOKE or ALTER statement}
\`\`\`

### MEDIUM Severity
{Same format}

### LOW Severity
{Same format}

## Recommendations
{Numbered list of top priority actions}

---
*Generated by Security Audit Subagent*

## Rules
- ALL SQL output is for copy-paste review only — never suggest auto-execution.
- Cap results to top 20 findings per severity level.
- If a query fails, note the error and continue with other checks.
- System users (DBC, SYSLIB, SYSTEMFE, etc.) are excluded from findings.
- Use clear Teradata SQL syntax for all remediation steps.`;
}

export function getSecurityAuditConfig(ctx: SubagentContext) {
  const scope = ctx.params['scope'] || 'system-wide';
  return {
    systemPrompt: buildSecuritySystemPrompt(scope),
    toolFilter: SECURITY_TOOLS,
    maxToolRounds: MAX_TOOL_ROUNDS,
    maxTokens: 8192,
    initialMessage: `Please perform a security audit for scope: ${scope}. Follow the analysis checklist in your instructions and produce a prioritized findings report.`,
  };
}

export async function runSecurityAudit(ctx: SubagentContext): Promise<SubagentRunResult> {
  const scope = ctx.params['scope'] || 'system-wide';

  const { client, modelId } = await getBedrockClient();
  const allTools = await getMcpToolsForClaude();

  // Filter to only security-relevant tools
  const tools = allTools.filter((t) => SECURITY_TOOLS.includes(t.name));

  const systemPrompt = buildSecuritySystemPrompt(scope);

  const conversationMessages: Array<{
    role: 'user' | 'assistant';
    content: string | Array<Record<string, unknown>>;
  }> = [
    {
      role: 'user',
      content: `Please perform a security audit for scope: ${scope}. Follow the analysis checklist in your instructions and produce a prioritized findings report.`,
    },
  ];

  let outputText = '';
  let round = 0;

  while (round < MAX_TOOL_ROUNDS) {
    round++;

    const requestParams: Record<string, unknown> = {
      model: modelId,
      max_tokens: 8192,
      system: systemPrompt,
      messages: conversationMessages,
    };
    if (tools.length > 0) {
      requestParams.tools = tools;
    }

    const response = await (client.messages.create as (params: Record<string, unknown>) => Promise<any>)(requestParams);

    // Collect text from this response
    for (const block of response.content) {
      if (block.type === 'text') {
        outputText += block.text;
      }
    }

    // Check if Claude wants to use tools
    if (response.stop_reason === 'tool_use') {
      const toolUseBlocks = response.content.filter((block: any) => block.type === 'tool_use');
      if (toolUseBlocks.length === 0) break;

      // Add assistant message with tool_use to conversation
      conversationMessages.push({
        role: 'assistant',
        content: response.content,
      });

      // Execute each tool and build tool_result blocks
      const toolResults: Array<Record<string, unknown>> = [];
      for (const toolBlock of toolUseBlocks) {
        const result = await executeTool(toolBlock.name, toolBlock.input as Record<string, unknown>);
        toolResults.push({
          type: 'tool_result',
          tool_use_id: toolBlock.id,
          content: result,
        });
      }

      // Add tool results as user message and loop back
      conversationMessages.push({
        role: 'user',
        content: toolResults,
      });
      continue;
    }

    // No tool use — done
    break;
  }

  return { content: outputText };
}
